export const INTENT_REGISTRY = [
  {
    id: "supabase-auth-login",
    capability: "login",
    providerId: "supabase",
    taskId: "backend",
    recommendationTitle: "Recommended backend: Supabase",
    nextStep: "Next step: open Services → Backend → Supabase",
    reason: "Supabase Auth is a good fit for login and signup flows.",
    keywords: [
      "login",
      "log in",
      "sign in",
      "signin",
      "sign-in",
      "authentication",
      "auth",
      "user accounts",
      "accounts",
      "signup",
      "sign up",
      "register users",
      "user registration",
    ],
  },
  {
    id: "supabase-database",
    capability: "database",
    providerId: "supabase",
    taskId: "backend",
    recommendationTitle: "Recommended backend: Supabase",
    nextStep: "Next step: open Services → Backend → Supabase",
    reason: "Supabase is a good fit for database-backed app setup.",
    keywords: [
      "database",
      "db",
      "postgres",
      "postgresql",
      "data store",
      "store data",
      "save data",
      "persist data",
      "tables",
      "backend database",
    ],
  },
  {
    id: "supabase-storage",
    capability: "storage",
    providerId: "supabase",
    taskId: "backend",
    recommendationTitle: "Recommended backend: Supabase",
    nextStep: "Next step: open Services → Backend → Supabase",
    reason: "Supabase Storage is a good fit for file storage needs.",
    keywords: [
      "file storage",
      "storage",
      "upload files",
      "uploads",
      "store files",
      "image storage",
      "media storage",
      "bucket",
      "buckets",
    ],
  },
  {
    id: "stripe-payments",
    capability: "payments",
    providerId: "stripe",
    taskId: "payments",
    recommendationTitle: "Recommended backend: Stripe",
    nextStep: "Next step: open Services → Payments → Stripe",
    reason: "Stripe is a good fit for payments and checkout flows.",
    keywords: [
      "payments",
      "payment",
      "checkout",
      "billing",
      "subscriptions",
      "subscription",
      "charge customers",
      "card payments",
      "stripe",
    ],
  },
];

export function getIntentRegistry() {
  return INTENT_REGISTRY;
}
